name: Cache and artifacts for application

on:
  push:
    branches: [ main ]

jobs:
  Cache_and_artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: setup node js
        uses: actions/setup-node@v6.5.0
        with:
          node-version: 22.x
          cache: "npm"

      - name: install dependencies
        run: npm install

      - name: Fix permissions
        run: chmod +x node_modules/.bin/*

      - name: Build app
        run: npm run build

      - name: Artifacts collection
        uses: actions/upload-artifact@v7.0.1
        with:
          name: next js build
          path: ./dist/
